### This notebook contains:

* File inspection
* Column inspection
* Row counts
* Timestamp analysis
* Sampling-rate estimation
* Accelerometer/gyroscope alignment analysis

In [23]:
# Connect to the Drive dataset folder and list all CSV files
from pathlib import Path
import pandas as pd

DATA_DIR = Path("/content/drive/MyDrive/sample_data")

files = sorted(DATA_DIR.glob("*.csv"))

print(f"Number of CSV files found: {len(files)}")

for file in files:
    print(file.name)

Number of CSV files found: 20
112_PocketPhone_Accelerometer_(Samsung_S6).csv
112_PocketPhone_Gyroscope_(Samsung_S6).csv
13_PocketPhone_Accelerometer_(Samsung_S6).csv
13_PocketPhone_Gyroscope_(Samsung_S6).csv
23_PocketPhone_Accelerometer_(Samsung_S6).csv
23_PocketPhone_Gyroscope_(Samsung_S6).csv
24_PocketPhone_Accelerometer_(Samsung_S6).csv
24_PocketPhone_Gyroscope_(Samsung_S6).csv
2_PocketPhone_Accelerometer_(Samsung_S6).csv
2_PocketPhone_Gyroscope_(Samsung_S6).csv
49_PocketPhone_Accelerometer_(Samsung_S6).csv
49_PocketPhone_Gyroscope_(Samsung_S6).csv
52_PocketPhone_Accelerometer_(Samsung_S6).csv
52_PocketPhone_Gyroscope_(Samsung_S6).csv
55_PocketPhone_Accelerometer_(Samsung_S6).csv
55_PocketPhone_Gyroscope_(Samsung_S6).csv
70_PocketPhone_Accelerometer_(Samsung_S6).csv
70_PocketPhone_Gyroscope_(Samsung_S6).csv
78_PocketPhone_Accelerometer_(Samsung_S6).csv
78_PocketPhone_Gyroscope_(Samsung_S6).csv

In [7]:
# Inspect columns, rows, and sample values
for file in files:
    df = pd.read_csv(file)

    print("=" * 80)
    print(f"File: {file.name}")
    print(f"Rows: {len(df):,}")
    print(f"Columns: {list(df.columns)}")
    print("\nData types:")
    print(df.dtypes)
    print("\nFirst 3 rows:")
    display(df.head(3))

================================================================================
File: 112_PocketPhone_Accelerometer_(Samsung_S6).csv
Rows: 26,343
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue     Yvalue    Zvalue                     time
0    0 -0.699107  12.452243  2.774880  2017-06-08 12:51:01.535
1    1 -3.429694  12.279860  2.568978  2017-06-08 12:51:01.545
2    2 -5.578490  11.931504  4.232949  2017-06-08 12:51:01.555

================================================================================
File: 112_PocketPhone_Gyroscope_(Samsung_S6).csv
Rows: 26,343
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue    Yvalue    Zvalue                     time
0    0  3.843474 -0.198139 -0.021305  2017-06-08 12:51:01.536
1    1  4.048005 -0.630637 -0.045806  2017-06-08 12:51:01.545
2    2  3.910586 -1.280448  0.123571  2017-06-08 12:51:01.555

================================================================================
File: 13_PocketPhone_Accelerometer_(Samsung_S6).csv
Rows: 30,459
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue    Yvalue    Zvalue                     time
0    0  1.709460 -8.427590  1.788469  2017-04-30 13:43:48.135
1    1  1.841141 -8.421604  2.276886  2017-04-30 13:43:48.145
2    2  1.766921 -8.445546  2.078167  2017-04-30 13:43:48.156

================================================================================
File: 13_PocketPhone_Gyroscope_(Samsung_S6).csv
Rows: 30,459
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue    Yvalue    Zvalue                     time
0    0 -0.291882 -0.509196 -0.285491  2017-04-30 13:43:48.135
1    1 -0.229032 -0.484695 -0.206661  2017-04-30 13:43:48.145
2    2 -0.147006 -0.353668 -0.145941  2017-04-30 13:43:48.155

================================================================================
File: 23_PocketPhone_Accelerometer_(Samsung_S6).csv
Rows: 34,105
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue     Yvalue    Zvalue                     time
0    0 -0.156820  10.687716 -0.839168  2017-05-04 13:43:24.261
1    1 -0.160412  11.465832  0.017957  2017-05-04 13:43:24.271
2    2 -0.076614  12.257115  0.442927  2017-05-04 13:43:24.281

================================================================================
File: 23_PocketPhone_Gyroscope_(Samsung_S6).csv
Rows: 34,105
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue    Yvalue    Zvalue                     time
0    0 -0.514523 -0.298274  0.377104  2017-05-04 13:43:24.261
1    1 -0.305731  0.070307  0.540089  2017-05-04 13:43:24.270
2    2 -0.118244  0.434628  0.694552  2017-05-04 13:43:24.281

================================================================================
File: 24_PocketPhone_Accelerometer_(Samsung_S6).csv
Rows: 23,297
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue    Yvalue    Zvalue                     time
0    0  1.115698 -3.190274 -6.921637  2017-05-04 16:53:16.366
1    1  1.423353 -3.786430 -6.609194  2017-05-04 16:53:16.378
2    2  0.548272 -6.329072 -3.350685  2017-05-04 16:53:16.388

================================================================================
File: 24_PocketPhone_Gyroscope_(Samsung_S6).csv
Rows: 23,296
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue    Yvalue    Zvalue                     time
0    0 -0.022371 -0.896953  0.639159  2017-05-04 16:53:16.367
1    1 -0.951281 -1.555286  0.344080  2017-05-04 16:53:16.379
2    2 -1.906823 -1.818406 -0.058590  2017-05-04 16:53:16.389

================================================================================
File: 2_PocketPhone_Accelerometer_(Samsung_S6).csv
Rows: 35,105
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue    Yvalue    Zvalue                     time
0    0  1.978808 -1.114501  3.514688  2017-04-17 14:44:43.026
1    1  0.810437 -2.832341  2.801216  2017-04-17 14:44:43.036
2    2 -0.252588 -5.337873  2.322376  2017-04-17 14:44:43.045

================================================================================
File: 2_PocketPhone_Gyroscope_(Samsung_S6).csv
Rows: 35,105
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue    Yvalue    Zvalue                     time
0    0  0.579504 -0.647681  0.233293  2017-04-17 14:44:43.026
1    1  1.075917 -1.181378  0.243946  2017-04-17 14:44:43.036
2    2  1.538242 -1.643703  0.274838  2017-04-17 14:44:43.045

================================================================================
File: 49_PocketPhone_Accelerometer_(Samsung_S6).csv
Rows: 25,954
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue     Yvalue    Zvalue                     time
0    0  0.586579 -10.023325 -1.152808  2017-05-12 12:55:22.904
1    1  0.566229 -10.169372 -1.363498  2017-05-12 12:55:22.913
2    2  0.654814 -10.257957 -1.540669  2017-05-12 12:55:22.924

================================================================================
File: 49_PocketPhone_Gyroscope_(Samsung_S6).csv
Rows: 25,955
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue    Yvalue    Zvalue                     time
0    0 -0.269512 -0.591222  0.041545  2017-05-12 12:55:22.904
1    1 -0.285491 -0.548611  0.023436  2017-05-12 12:55:22.912
2    2 -0.317449 -0.504935  0.004261  2017-05-12 12:55:22.924

================================================================================
File: 52_PocketPhone_Accelerometer_(Samsung_S6).csv
Rows: 25,029
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue     Yvalue    Zvalue                     time
0    0  1.911770  11.638214  2.293645  2017-05-15 13:53:08.883
1    1  1.254562  11.930307  1.842338  2017-05-15 13:53:08.892
2    2  0.486023  11.635820  1.266533  2017-05-15 13:53:08.902

================================================================================
File: 52_PocketPhone_Gyroscope_(Samsung_S6).csv
Rows: 25,029
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue    Yvalue    Zvalue                     time
0    0  0.354733  0.224771 -0.564590  2017-05-15 13:53:08.883
1    1  0.270577  0.260990 -0.371777  2017-05-15 13:53:08.892
2    2  0.159790  0.521980 -0.115049  2017-05-15 13:53:08.902

================================================================================
File: 55_PocketPhone_Accelerometer_(Samsung_S6).csv
Rows: 29,894
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue    Yvalue    Zvalue                     time
0    0 -0.283713  9.315839  1.221043  2017-05-15 17:24:15.187
1    1  0.171185  9.096769  0.742203  2017-05-15 17:24:15.195
2    2  0.283713  9.059659  0.380678  2017-05-15 17:24:15.205

================================================================================
File: 55_PocketPhone_Gyroscope_(Samsung_S6).csv
Rows: 29,894
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue    Yvalue    Zvalue                     time
0    0  0.397344  0.416518 -0.019175  2017-05-15 17:24:15.187
1    1  0.411192  0.446346  0.050067  2017-05-15 17:24:15.195
2    2  0.426106  0.406931  0.166181  2017-05-15 17:24:15.205

================================================================================
File: 70_PocketPhone_Accelerometer_(Samsung_S6).csv
Rows: 28,173
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue     Yvalue    Zvalue                     time
0    0  4.448427 -10.964247 -0.081403  2017-05-22 11:07:16.545
1    1  4.303577 -11.243171 -0.087388  2017-05-22 11:07:16.556
2    2  3.575740 -10.417171  0.582988  2017-05-22 11:07:16.565

================================================================================
File: 70_PocketPhone_Gyroscope_(Samsung_S6).csv
Rows: 28,174
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue    Yvalue    Zvalue                     time
0    0 -0.913997 -1.635181  0.363255  2017-05-22 11:07:16.545
1    1 -0.990696 -1.390170  0.188552  2017-05-22 11:07:16.555
2    2 -0.997088 -1.137702  0.094809  2017-05-22 11:07:16.565

================================================================================
File: 78_PocketPhone_Accelerometer_(Samsung_S6).csv
Rows: 22,200
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue     Yvalue    Zvalue                     time
0    0  1.714248  11.247959  0.548272  2017-05-23 15:27:11.124
1    1  0.735020  10.609905  5.542577  2017-05-23 15:27:11.134
2    2 -0.945710  10.007763  4.672285  2017-05-23 15:27:11.145

================================================================================
File: 78_PocketPhone_Gyroscope_(Samsung_S6).csv
Rows: 22,199
Columns: ['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 3 rows:

   EID    Xvalue    Yvalue    Zvalue                     time
0    0  1.742773 -0.371777  0.046872  2017-05-23 15:27:11.124
1    1  2.188053 -1.222924 -0.061785  2017-05-23 15:27:11.134
2    2  3.053048 -2.553439 -0.057524  2017-05-23 15:27:11.144

In [22]:
# Identify and list accelerometer and gyroscope files
accelerometer_files = []
gyroscope_files = []

for file in files:
    filename = file.name.lower()

    if "accelerometer" in filename:
        accelerometer_files.append(file)
    elif "gyroscope" in filename:
        gyroscope_files.append(file)

print(f"Accelerometer files: {len(accelerometer_files)}")
print(f"Gyroscope files: {len(gyroscope_files)}")

print("\nAccelerometer files:")
for file in accelerometer_files:
    print(file.name)

print("\nGyroscope files:")
for file in gyroscope_files:
    print(file.name)

Accelerometer files: 10
Gyroscope files: 10

Accelerometer files:
112_PocketPhone_Accelerometer_(Samsung_S6).csv
13_PocketPhone_Accelerometer_(Samsung_S6).csv
23_PocketPhone_Accelerometer_(Samsung_S6).csv
24_PocketPhone_Accelerometer_(Samsung_S6).csv
2_PocketPhone_Accelerometer_(Samsung_S6).csv
49_PocketPhone_Accelerometer_(Samsung_S6).csv
52_PocketPhone_Accelerometer_(Samsung_S6).csv
55_PocketPhone_Accelerometer_(Samsung_S6).csv
70_PocketPhone_Accelerometer_(Samsung_S6).csv
78_PocketPhone_Accelerometer_(Samsung_S6).csv

Gyroscope files:
112_PocketPhone_Gyroscope_(Samsung_S6).csv
13_PocketPhone_Gyroscope_(Samsung_S6).csv
23_PocketPhone_Gyroscope_(Samsung_S6).csv
24_PocketPhone_Gyroscope_(Samsung_S6).csv
2_PocketPhone_Gyroscope_(Samsung_S6).csv
49_PocketPhone_Gyroscope_(Samsung_S6).csv
52_PocketPhone_Gyroscope_(Samsung_S6).csv
55_PocketPhone_Gyroscope_(Samsung_S6).csv
70_PocketPhone_Gyroscope_(Samsung_S6).csv
78_PocketPhone_Gyroscope_(Samsung_S6).csv

In [24]:
# Compare row counts
print("Accelerometer row counts:")
for file in sorted(accelerometer_files):
    df = pd.read_csv(file)
    print(f"{file.name}: {len(df):,} rows")

print("\nGyroscope row counts:")
for file in sorted(gyroscope_files):
    df = pd.read_csv(file)
    print(f"{file.name}: {len(df):,} rows")

Accelerometer row counts:
112_PocketPhone_Accelerometer_(Samsung_S6).csv: 26,343 rows
13_PocketPhone_Accelerometer_(Samsung_S6).csv: 30,459 rows
23_PocketPhone_Accelerometer_(Samsung_S6).csv: 34,105 rows
24_PocketPhone_Accelerometer_(Samsung_S6).csv: 23,297 rows
2_PocketPhone_Accelerometer_(Samsung_S6).csv: 35,105 rows
49_PocketPhone_Accelerometer_(Samsung_S6).csv: 25,954 rows
52_PocketPhone_Accelerometer_(Samsung_S6).csv: 25,029 rows
55_PocketPhone_Accelerometer_(Samsung_S6).csv: 29,894 rows
70_PocketPhone_Accelerometer_(Samsung_S6).csv: 28,173 rows
78_PocketPhone_Accelerometer_(Samsung_S6).csv: 22,200 rows

Gyroscope row counts:
112_PocketPhone_Gyroscope_(Samsung_S6).csv: 26,343 rows
13_PocketPhone_Gyroscope_(Samsung_S6).csv: 30,459 rows
23_PocketPhone_Gyroscope_(Samsung_S6).csv: 34,105 rows
24_PocketPhone_Gyroscope_(Samsung_S6).csv: 23,296 rows
2_PocketPhone_Gyroscope_(Samsung_S6).csv: 35,105 rows
49_PocketPhone_Gyroscope_(Samsung_S6).csv: 25,955 rows
52_PocketPhone_Gyroscope_(Samsung_S6).csv: 25,029 rows
55_PocketPhone_Gyroscope_(Samsung_S6).csv: 29,894 rows
70_PocketPhone_Gyroscope_(Samsung_S6).csv: 28,174 rows
78_PocketPhone_Gyroscope_(Samsung_S6).csv: 22,199 rows

In [25]:
# Inspect user 2
import re
import numpy as np
import pandas as pd

# Select one user to inspect in detail
user_id = "2"

acc_file = next(
    file for file in accelerometer_files
    if file.name.startswith(f"{user_id}_")
)

gyro_file = next(
    file for file in gyroscope_files
    if file.name.startswith(f"{user_id}_")
)

acc_df = pd.read_csv(acc_file)
gyro_df = pd.read_csv(gyro_file)

print("Accelerometer columns:")
print(acc_df.columns.tolist())

print("\nGyroscope columns:")
print(gyro_df.columns.tolist())

print("\nAccelerometer data types:")
print(acc_df.dtypes)

print("\nGyroscope data types:")
print(gyro_df.dtypes)

print("\nFirst 5 accelerometer rows:")
display(acc_df.head())

print("\nFirst 5 gyroscope rows:")
display(gyro_df.head())

Accelerometer columns:
['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Gyroscope columns:
['EID', 'Xvalue', 'Yvalue', 'Zvalue', 'time']

Accelerometer data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

Gyroscope data types:
EID         int64
Xvalue    float64
Yvalue    float64
Zvalue    float64
time       object
dtype: object

First 5 accelerometer rows:

   EID    Xvalue     Yvalue    Zvalue                     time
0    0  1.978808  -1.114501  3.514688  2017-04-17 14:44:43.026
1    1  0.810437  -2.832341  2.801216  2017-04-17 14:44:43.036
2    2 -0.252588  -5.337873  2.322376  2017-04-17 14:44:43.045
3    3 -1.994370  -8.580819  0.926556  2017-04-17 14:44:43.057
4    4 -3.323152 -11.498154 -0.196325  2017-04-17 14:44:43.066

First 5 gyroscope rows:

   EID    Xvalue    Yvalue    Zvalue                     time
0    0  0.579504 -0.647681  0.233293  2017-04-17 14:44:43.026
1    1  1.075917 -1.181378  0.243946  2017-04-17 14:44:43.036
2    2  1.538242 -1.643703  0.274838  2017-04-17 14:44:43.045
3    3  1.940912 -1.842908  0.297209  2017-04-17 14:44:43.057
4    4  2.179531 -1.902562  0.373908  2017-04-17 14:44:43.066

In [27]:
# Display timestamp examples and recording start/end times
print("Accelerometer time values:")
display(acc_df["time"].head(10))

print("\nGyroscope time values:")
display(gyro_df["time"].head(10))

print("\nLast accelerometer time:")
print(acc_df["time"].tail(1).iloc[0])

print("\nLast gyroscope time:")
print(gyro_df["time"].tail(1).iloc[0])

Accelerometer time values:

0    2017-04-17 14:44:43.026
1    2017-04-17 14:44:43.036
2    2017-04-17 14:44:43.045
3    2017-04-17 14:44:43.057
4    2017-04-17 14:44:43.066
5    2017-04-17 14:44:43.075
6    2017-04-17 14:44:43.085
7    2017-04-17 14:44:43.095
8    2017-04-17 14:44:43.105
9    2017-04-17 14:44:43.116
Name: time, dtype: object

Gyroscope time values:

0    2017-04-17 14:44:43.026
1    2017-04-17 14:44:43.036
2    2017-04-17 14:44:43.045
3    2017-04-17 14:44:43.057
4    2017-04-17 14:44:43.066
5    2017-04-17 14:44:43.075
6    2017-04-17 14:44:43.085
7    2017-04-17 14:44:43.095
8    2017-04-17 14:44:43.105
9    2017-04-17 14:44:43.117
Name: time, dtype: object

Last accelerometer time:
2017-04-17 15:18:11.420

Last gyroscope time:
2017-04-17 15:18:11.420

In [28]:
# Calculate timestamp differences and estimate the sensor frequency as approximately 100 Hz
def inspect_timestamps(df, name):
    # Convert timestamps into elapsed time
    time_values = pd.to_datetime(df["time"].astype(str))

    time_differences = time_values.diff().dt.total_seconds().dropna()

    print(f"\n{name}")
    print("-" * 50)
    print(f"Timestamp values: {len(time_values):,}")
    print(f"Missing timestamps: {time_values.isna().sum()}")
    print(f"Time is monotonic: {time_values.is_monotonic_increasing}")
    print(f"Total duration: {time_values.iloc[-1] - time_values.iloc[0]}")
    print(f"Minimum time difference: {time_differences.min():.6f} seconds")
    print(f"Median time difference: {time_differences.median():.6f} seconds")
    print(f"Maximum time difference: {time_differences.max():.6f} seconds")

    estimated_frequency = 1 / time_differences.median()

    print(f"Estimated sampling frequency: {estimated_frequency:.2f} Hz")


inspect_timestamps(acc_df, "Accelerometer")
inspect_timestamps(gyro_df, "Gyroscope")

Accelerometer
--------------------------------------------------
Timestamp values: 35,105
Missing timestamps: 0
Time is monotonic: True
Total duration: 0 days 00:33:28.394000
Minimum time difference: 0.000000 seconds
Median time difference: 0.010000 seconds
Maximum time difference: 1659.045000 seconds
Estimated sampling frequency: 100.00 Hz

Gyroscope
--------------------------------------------------
Timestamp values: 35,105
Missing timestamps: 0
Time is monotonic: True
Total duration: 0 days 00:33:28.394000
Minimum time difference: 0.000000 seconds
Median time difference: 0.010000 seconds
Maximum time difference: 1659.044000 seconds
Estimated sampling frequency: 100.00 Hz

In [29]:
# Match each user’s accelerometer file with their gyroscope file and compare row counts
def get_user_id(file):
    return re.match(r"^(\d+)_", file.name).group(1)


acc_by_user = {get_user_id(file): file for file in accelerometer_files}
gyro_by_user = {get_user_id(file): file for file in gyroscope_files}

print("User pairing summary")
print("-" * 70)

for user_id in sorted(acc_by_user, key=int):
    acc_data = pd.read_csv(acc_by_user[user_id])
    gyro_data = pd.read_csv(gyro_by_user[user_id])

    print(
        f"User {user_id:>3}: "
        f"Accelerometer = {len(acc_data):>6,} rows | "
        f"Gyroscope = {len(gyro_data):>6,} rows | "
        f"Difference = {len(acc_data) - len(gyro_data):>2}"
    )

User pairing summary
----------------------------------------------------------------------
User   2: Accelerometer = 35,105 rows | Gyroscope = 35,105 rows | Difference =  0
User  13: Accelerometer = 30,459 rows | Gyroscope = 30,459 rows | Difference =  0
User  23: Accelerometer = 34,105 rows | Gyroscope = 34,105 rows | Difference =  0
User  24: Accelerometer = 23,297 rows | Gyroscope = 23,296 rows | Difference =  1
User  49: Accelerometer = 25,954 rows | Gyroscope = 25,955 rows | Difference = -1
User  52: Accelerometer = 25,029 rows | Gyroscope = 25,029 rows | Difference =  0
User  55: Accelerometer = 29,894 rows | Gyroscope = 29,894 rows | Difference =  0
User  70: Accelerometer = 28,173 rows | Gyroscope = 28,174 rows | Difference = -1
User  78: Accelerometer = 22,200 rows | Gyroscope = 22,199 rows | Difference =  1
User 112: Accelerometer = 26,343 rows | Gyroscope = 26,343 rows | Difference =  0

In [31]:
# Check duplicate timestamps, large gaps, and exact timestamp overlap for user 2
def analyze_pair(user_id):
    acc_file = acc_by_user[user_id]
    gyro_file = gyro_by_user[user_id]

    acc = pd.read_csv(acc_file)
    gyro = pd.read_csv(gyro_file)

    # Convert timestamp strings into datetime values
    acc["time"] = pd.to_datetime(acc["time"])
    gyro["time"] = pd.to_datetime(gyro["time"])

    # Calculate time differences in seconds
    acc_diffs = acc["time"].diff().dt.total_seconds().dropna()
    gyro_diffs = gyro["time"].diff().dt.total_seconds().dropna()

    print(f"USER {user_id}")
    print("=" * 70)

    print(f"Accelerometer rows: {len(acc):,}")
    print(f"Gyroscope rows:     {len(gyro):,}")

    print("\nAccelerometer timing:")
    print(f"  Duplicate timestamps: {(acc['time'].diff() == pd.Timedelta(0)).sum()}")
    print(f"  Gaps greater than 20 ms: {(acc_diffs > 0.020).sum()}")
    print(f"  Largest gap: {acc_diffs.max():.3f} seconds")

    print("\nGyroscope timing:")
    print(f"  Duplicate timestamps: {(gyro['time'].diff() == pd.Timedelta(0)).sum()}")
    print(f"  Gaps greater than 20 ms: {(gyro_diffs > 0.020).sum()}")
    print(f"  Largest gap: {gyro_diffs.max():.3f} seconds")

    # Compare exact timestamp sequences
    common_times = set(acc["time"]).intersection(set(gyro["time"]))

    print("\nTimestamp alignment:")
    print(f"  Common timestamps: {len(common_times):,}")
    print(f"  Accelerometer-only timestamps: {len(set(acc['time']) - set(gyro['time']))}")
    print(f"  Gyroscope-only timestamps: {len(set(gyro['time']) - set(acc['time']))}")

    print("\nFirst 10 time differences:")
    print("Accelerometer:", acc_diffs.head(10).tolist())
    print("Gyroscope:    ", gyro_diffs.head(10).tolist())


analyze_pair("2")

USER 2
======================================================================
Accelerometer rows: 35,105
Gyroscope rows:     35,105

Accelerometer timing:
  Duplicate timestamps: 174
  Gaps greater than 20 ms: 42
  Largest gap: 1659.045 seconds

Gyroscope timing:
  Duplicate timestamps: 264
  Gaps greater than 20 ms: 63
  Largest gap: 1659.044 seconds

Timestamp alignment:
  Common timestamps: 20,671
  Accelerometer-only timestamps: 14260
  Gyroscope-only timestamps: 14170

First 10 time differences:
Accelerometer: [0.01, 0.009, 0.012, 0.009, 0.009, 0.01, 0.01, 0.01, 0.011, 0.01]
Gyroscope:     [0.01, 0.009, 0.012, 0.009, 0.009, 0.01, 0.01, 0.01, 0.012, 0.009]

In [32]:
# Perform the same timestamp analysis for users 24, 49, 70, and 78
for user_id in ["24", "49", "70", "78"]:
    analyze_pair(user_id)

USER 24
======================================================================
Accelerometer rows: 23,297
Gyroscope rows:     23,296

Accelerometer timing:
  Duplicate timestamps: 90
  Gaps greater than 20 ms: 18
  Largest gap: 2723.464 seconds

Gyroscope timing:
  Duplicate timestamps: 141
  Gaps greater than 20 ms: 29
  Largest gap: 2723.463 seconds

Timestamp alignment:
  Common timestamps: 12,913
  Accelerometer-only timestamps: 10294
  Gyroscope-only timestamps: 10242

First 10 time differences:
Accelerometer: [0.012, 0.01, 0.007, 0.01, 0.01, 0.01, 0.01, 0.01, 0.011, 0.01]
Gyroscope:     [0.012, 0.01, 0.006, 0.01, 0.01, 0.011, 0.009, 0.01, 0.012, 0.01]
USER 49
======================================================================
Accelerometer rows: 25,954
Gyroscope rows:     25,955

Accelerometer timing:
  Duplicate timestamps: 191
  Gaps greater than 20 ms: 29
  Largest gap: 15369.927 seconds

Gyroscope timing:
  Duplicate timestamps: 157
  Gaps greater than 20 ms: 20
  Largest gap: 15369.918 seconds

Timestamp alignment:
  Common timestamps: 15,635
  Accelerometer-only timestamps: 10128
  Gyroscope-only timestamps: 10163

First 10 time differences:
Accelerometer: [0.009, 0.011, 0.013, 0.007, 0.01, 0.009, 0.011, 0.011, 0.012, 0.01]
Gyroscope:     [0.008, 0.012, 0.012, 0.008, 0.01, 0.009, 0.01, 0.011, 0.012, 0.01]
USER 70
======================================================================
Accelerometer rows: 28,173
Gyroscope rows:     28,174

Accelerometer timing:
  Duplicate timestamps: 192
  Gaps greater than 20 ms: 28
  Largest gap: 1880.698 seconds

Gyroscope timing:
  Duplicate timestamps: 125
  Gaps greater than 20 ms: 16
  Largest gap: 1880.698 seconds

Timestamp alignment:
  Common timestamps: 15,756
  Accelerometer-only timestamps: 12225
  Gyroscope-only timestamps: 12293

First 10 time differences:
Accelerometer: [0.011, 0.009, 0.01, 0.01, 0.01, 0.01, 0.012, 0.011, 0.007, 0.01]
Gyroscope:     [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.011, 0.011, 0.007, 0.01]
USER 78
======================================================================
Accelerometer rows: 22,200
Gyroscope rows:     22,199

Accelerometer timing:
  Duplicate timestamps: 204
  Gaps greater than 20 ms: 41
  Largest gap: 1243.912 seconds

Gyroscope timing:
  Duplicate timestamps: 145
  Gaps greater than 20 ms: 24
  Largest gap: 1243.923 seconds

Timestamp alignment:
  Common timestamps: 13,002
  Accelerometer-only timestamps: 8994
  Gyroscope-only timestamps: 9052

First 10 time differences:
Accelerometer: [0.01, 0.011, 0.009, 0.01, 0.01, 0.011, 0.01, 0.009, 0.01, 0.011]
Gyroscope:     [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]

In [33]:
# Summarize duplicates and large gaps for every user
print("Timestamp quality across all users")
print("=" * 90)

for user_id in sorted(acc_by_user, key=int):
    acc = pd.read_csv(acc_by_user[user_id])
    gyro = pd.read_csv(gyro_by_user[user_id])

    acc["time"] = pd.to_datetime(acc["time"])
    gyro["time"] = pd.to_datetime(gyro["time"])

    acc_diffs = acc["time"].diff().dt.total_seconds().dropna()
    gyro_diffs = gyro["time"].diff().dt.total_seconds().dropna()

    print(
        f"User {user_id:>3} | "
        f"Acc duplicate: {(acc_diffs == 0).sum():>3} | "
        f"Gyro duplicate: {(gyro_diffs == 0).sum():>3} | "
        f"Acc gaps >20ms: {(acc_diffs > 0.020).sum():>3} | "
        f"Gyro gaps >20ms: {(gyro_diffs > 0.020).sum():>3}"
    )

Timestamp quality across all users
==========================================================================================
User   2 | Acc duplicate: 174 | Gyro duplicate: 264 | Acc gaps >20ms:  42 | Gyro gaps >20ms:  63
User  13 | Acc duplicate: 241 | Gyro duplicate: 176 | Acc gaps >20ms:  40 | Gyro gaps >20ms:  31
User  23 | Acc duplicate: 270 | Gyro duplicate: 166 | Acc gaps >20ms:  41 | Gyro gaps >20ms:  27
User  24 | Acc duplicate:  90 | Gyro duplicate: 141 | Acc gaps >20ms:  18 | Gyro gaps >20ms:  29
User  49 | Acc duplicate: 191 | Gyro duplicate: 157 | Acc gaps >20ms:  29 | Gyro gaps >20ms:  20
User  52 | Acc duplicate:  98 | Gyro duplicate: 186 | Acc gaps >20ms:  18 | Gyro gaps >20ms:  46
User  55 | Acc duplicate: 196 | Gyro duplicate: 132 | Acc gaps >20ms:  28 | Gyro gaps >20ms:  21
User  70 | Acc duplicate: 192 | Gyro duplicate: 125 | Acc gaps >20ms:  28 | Gyro gaps >20ms:  16
User  78 | Acc duplicate: 204 | Gyro duplicate: 145 | Acc gaps >20ms:  41 | Gyro gaps >20ms:  24
User 112 | Acc duplicate: 125 | Gyro duplicate: 176 | Acc gaps >20ms:  24 | Gyro gaps >20ms:  35

In [34]:
# Confirm that EID correctly aligns accelerometer and gyroscope rows for user 2
def analyze_eid_alignment(user_id):
    acc = pd.read_csv(acc_by_user[user_id])
    gyro = pd.read_csv(gyro_by_user[user_id])

    acc["time"] = pd.to_datetime(acc["time"])
    gyro["time"] = pd.to_datetime(gyro["time"])

    merged = pd.merge(
        acc,
        gyro,
        on="EID",
        how="inner",
        suffixes=("_acc", "_gyro")
    )

    # Difference between accelerometer and gyroscope timestamps
    timestamp_difference = (
        merged["time_acc"] - merged["time_gyro"]
    ).dt.total_seconds().abs()

    print(f"USER {user_id}")
    print("=" * 70)
    print(f"Accelerometer rows: {len(acc):,}")
    print(f"Gyroscope rows:     {len(gyro):,}")
    print(f"Rows matched by EID: {len(merged):,}")

    print("\nEID information:")
    print(f"Accelerometer EIDs unique: {acc['EID'].is_unique}")
    print(f"Gyroscope EIDs unique:     {gyro['EID'].is_unique}")
    print(f"Accelerometer EIDs monotonic: {acc['EID'].is_monotonic_increasing}")
    print(f"Gyroscope EIDs monotonic:     {gyro['EID'].is_monotonic_increasing}")

    print("\nTimestamp differences after matching by EID:")
    print(f"Maximum difference: {timestamp_difference.max():.6f} seconds")
    print(f"Mean difference:    {timestamp_difference.mean():.6f} seconds")
    print(f"Median difference:  {timestamp_difference.median():.6f} seconds")
    print(f"Differences > 20 ms: {(timestamp_difference > 0.020).sum()}")

    print("\nFirst 10 matched rows:")
    display(
        merged[
            [
                "EID",
                "time_acc",
                "time_gyro",
                "Xvalue_acc",
                "Xvalue_gyro"
            ]
        ].head(10)
    )

    return merged


merged_user_2 = analyze_eid_alignment("2")

USER 2
======================================================================
Accelerometer rows: 35,105
Gyroscope rows:     35,105
Rows matched by EID: 35,105

EID information:
Accelerometer EIDs unique: True
Gyroscope EIDs unique:     True
Accelerometer EIDs monotonic: True
Gyroscope EIDs monotonic:     True

Timestamp differences after matching by EID:
Maximum difference: 0.071000 seconds
Mean difference:    0.000446 seconds
Median difference:  0.000000 seconds
Differences > 20 ms: 3

First 10 matched rows:

,EID,time_acc,time_gyro,Xvalue_acc,Xvalue_gyro
0,0,2017-04-17 14:44:43.026,2017-04-17 14:44:43.026,1.978808,0.579504
1,1,2017-04-17 14:44:43.036,2017-04-17 14:44:43.036,0.810437,1.075917
2,2,2017-04-17 14:44:43.045,2017-04-17 14:44:43.045,-0.252588,1.538242
3,3,2017-04-17 14:44:43.057,2017-04-17 14:44:43.057,-1.994370,1.940912
4,4,2017-04-17 14:44:43.066,2017-04-17 14:44:43.066,-3.323152,2.179531
5,5,2017-04-17 14:44:43.075,2017-04-17 14:44:43.075,-4.203021,2.304167
6,6,2017-04-17 14:44:43.085,2017-04-17 14:44:43.085,-4.197036,2.385127
7,7,2017-04-17 14:44:43.095,2017-04-17 14:44:43.095,-3.604471,2.405367
8,8,2017-04-17 14:44:43.105,2017-04-17 14:44:43.105,-2.043451,2.346778
9,9,2017-04-17 14:44:43.116,2017-04-17 14:44:43.117,-0.408211,2.213619

In [35]:
# Confirm that nearly all rows match by EID for every user
print("EID alignment across all users")
print("=" * 90)

for user_id in sorted(acc_by_user, key=int):
    acc = pd.read_csv(acc_by_user[user_id])
    gyro = pd.read_csv(gyro_by_user[user_id])

    merged = pd.merge(acc, gyro, on="EID", how="inner")

    print(
        f"User {user_id:>3} | "
        f"Acc rows: {len(acc):>6,} | "
        f"Gyro rows: {len(gyro):>6,} | "
        f"Matched EIDs: {len(merged):>6,} | "
        f"Missing rows: {max(len(acc), len(gyro)) - len(merged):>2}"
    )

EID alignment across all users
==========================================================================================
User   2 | Acc rows: 35,105 | Gyro rows: 35,105 | Matched EIDs: 35,105 | Missing rows:  0
User  13 | Acc rows: 30,459 | Gyro rows: 30,459 | Matched EIDs: 30,459 | Missing rows:  0
User  23 | Acc rows: 34,105 | Gyro rows: 34,105 | Matched EIDs: 34,105 | Missing rows:  0
User  24 | Acc rows: 23,297 | Gyro rows: 23,296 | Matched EIDs: 23,296 | Missing rows:  1
User  49 | Acc rows: 25,954 | Gyro rows: 25,955 | Matched EIDs: 25,954 | Missing rows:  1
User  52 | Acc rows: 25,029 | Gyro rows: 25,029 | Matched EIDs: 25,029 | Missing rows:  0
User  55 | Acc rows: 29,894 | Gyro rows: 29,894 | Matched EIDs: 29,894 | Missing rows:  0
User  70 | Acc rows: 28,173 | Gyro rows: 28,174 | Matched EIDs: 28,173 | Missing rows:  1
User  78 | Acc rows: 22,200 | Gyro rows: 22,199 | Matched EIDs: 22,199 | Missing rows:  1
User 112 | Acc rows: 26,343 | Gyro rows: 26,343 | Matched EIDs: 26,343 | Missing rows:  0